### ISSUE TITLE
Model and Collection name fail in define

### ISSUE THREAD

**Issue by PereKastor** [metidia/generator-vinoga#9]
![image](https://cloud.githubusercontent.com/assets/2781201/5643861/7638798a-965d-11e4-8028-2433a8f7e59e.png)

Les noms du model et de la collection ne sont pas les meme dans le define et l'initialisation.

**Comment by nicoespeon** [comment]
Fixed in c0f3fcd0f76d21d64192a30d231f28512a2faa51
